export const RECIPE_WIDGET_URI = "ui://marco/recipe-card-v1.html";

// Recipe content is rendered with textContent, never interpolated into HTML.
export const recipeWidgetHtml = String.raw`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Marco recipe card</title><style>
:root{color-scheme:light dark;font-family:system-ui,sans-serif;color:light-dark(#211c17,#faf4e9);background:light-dark(#fffaf1,#24211c)}
*{box-sizing:border-box}body{margin:0;padding:20px}article{max-width:680px;margin:auto}.brand{font-size:12px;letter-spacing:.15em;text-transform:uppercase;color:light-dark(#a63d22,#ffaa8d)}h1{font-family:Georgia,serif;font-size:28px;line-height:1.15;margin:12px 0}p,li{line-height:1.55;overflow-wrap:anywhere}.muted{font-size:14px;opacity:.75}ul,ol{padding-left:24px}li{margin:6px 0}details{border-top:1px solid #8886;padding:14px 0}summary{cursor:pointer;font-weight:650}button{background:#b53c24;color:white;border:0;border-radius:12px;padding:13px 20px;font:inherit;font-weight:650;cursor:pointer}button:disabled{opacity:.55;cursor:default}button:focus-visible,a:focus-visible,summary:focus-visible{outline:3px solid #dd9560;outline-offset:4px}.actions{display:flex;align-items:center;flex-wrap:wrap;gap:14px;margin-top:18px}a{color:inherit}#status{min-height:24px;font-size:14px}[hidden]{display:none!important}@media(max-width:380px){body{padding:14px}h1{font-size:24px}}
</style></head><body><article aria-label="Marco recipe">
<div class="brand">Marco · Recipe preview</div><h1 id="title">Your recipe</h1><p id="description"></p><p id="facts" class="muted"></p>
<details open><summary>Ingredients</summary><ul id="ingredients"></ul></details>
<details><summary>Cooking steps</summary><ol id="steps"></ol></details>
<p class="muted">Review this recipe before saving. Saving adds it to your Marco account.</p>
<div class="actions"><button id="save" disabled>Save to Marco</button><a id="permissions" hidden target="_blank" rel="noopener noreferrer">Enable recipe saving</a><a id="saved" hidden target="_blank" rel="noopener noreferrer">Open saved recipe</a></div>
<p id="status" role="status" aria-live="polite">Connecting to ChatGPT…</p>
</article><script>
const byId=id=>document.getElementById(id),pending=new Map();let sequence=0,recipe=null,ready=false,saving=false;
function request(method,params){return new Promise((resolve,reject)=>{const id=++sequence;const timer=setTimeout(()=>{pending.delete(id);reject(new Error('The request timed out. You can retry safely.'));},30000);pending.set(id,{resolve,reject,timer});parent.postMessage({jsonrpc:'2.0',id,method,params},'*');});}
function notify(method,params){parent.postMessage({jsonrpc:'2.0',method,params},'*');}
function safeLink(id,url){const el=byId(id);el.hidden=true;try{const u=new URL(url);if(u.origin==='https://marco-eta-lyart.vercel.app'&&!u.username&&!u.password){el.href=u.href;el.hidden=false;}}catch{}}
function render(value){if(!value?.recipe||value.saved)return;recipe=value.recipe;byId('title').textContent=recipe.title;byId('description').textContent=recipe.description||'';byId('facts').textContent=[recipe.servings?recipe.servings+' servings':'',recipe.prep_time_minutes!=null?'Prep '+recipe.prep_time_minutes+' min':'',recipe.cook_time_minutes!=null?'Cook '+recipe.cook_time_minutes+' min':''].filter(Boolean).join(' · ');for(const [id,items] of [['ingredients',recipe.ingredients.map(i=>[i.amount,i.unit,i.name].filter(Boolean).join(' '))],['steps',recipe.steps]]){byId(id).replaceChildren();for(const text of items){const li=document.createElement('li');li.textContent=text;byId(id).append(li);}}safeLink('permissions',value.permission_url);byId('save').disabled=!ready||saving;byId('status').textContent=ready?'Ready to save.':'';notify('ui/notifications/size-changed',{height:document.documentElement.scrollHeight});}
addEventListener('message',event=>{if(event.source!==parent||!event.data||event.data.jsonrpc!=='2.0')return;const msg=event.data;if(pending.has(msg.id)){const p=pending.get(msg.id);pending.delete(msg.id);clearTimeout(p.timer);msg.error?p.reject(new Error(msg.error.message||'Request failed.')):p.resolve(msg.result);return;}if(msg.method==='ui/notifications/tool-result')render(msg.params?.structuredContent);});
byId('save').onclick=async()=>{if(!recipe||!ready||saving)return;saving=true;byId('save').disabled=true;byId('status').textContent='Saving…';try{const result=await request('tools/call',{name:'save_recipe',arguments:{recipe,confirmed:true}});if(result.isError)throw new Error(result.content?.find(c=>c.type==='text')?.text||'Could not save.');if(!result.structuredContent?.saved)throw new Error('Save could not be verified. Retry safely.');byId('status').textContent=result.structuredContent.already_saved?'Already saved in Marco.':'Saved to Marco.';byId('save').textContent='Saved';safeLink('saved',result.structuredContent.recipe?.url);byId('permissions').hidden=true;}catch(error){byId('status').textContent=error.message;saving=false;byId('save').disabled=false;}};
request('ui/initialize',{protocolVersion:'2026-01-26',appInfo:{name:'Marco recipe card',version:'0.2.0'},appCapabilities:{availableDisplayModes:['inline']}}).then(()=>{ready=true;notify('ui/notifications/initialized',{});byId('save').disabled=!recipe;byId('status').textContent=recipe?'Ready to save.':'Waiting for recipe…';}).catch(()=>{byId('status').textContent='This host cannot display interactive controls. Ask ChatGPT to save the recipe instead.';});
new ResizeObserver(()=>notify('ui/notifications/size-changed',{height:document.documentElement.scrollHeight})).observe(document.body);
</script></body></html>`;
