"use client";

import { useEffect, useState, useMemo, useRef } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import useSWR from "swr";
import { apiFetcher } from "@/lib/hooks/use-data";
import type { GroceryItem as GroceryItemType, GroceryList as GroceryListType } from "@/types";
import GroceryItem from "./GroceryItem";
import AddItemSheet from "./AddItemSheet";
import EditItemSheet from "./EditItemSheet";
import OrderOnlineSheet from "./OrderOnlineSheet";

// ─── Category config ──────────────────────────────────────────────────────────
const CATEGORY_CONFIG: Record<string, { label: string; emoji: string }> = {
  produce:   { label: "Produce",              emoji: "🥬" },
  protein:   { label: "Protein",              emoji: "🥩" },
  dairy:     { label: "Dairy & Eggs",         emoji: "🥛" },
  pantry:    { label: "Pantry",               emoji: "🥫" },
  canned:    { label: "Pantry",               emoji: "🥫" },
  spices:    { label: "Spices & Condiments",  emoji: "🧂" },
  spice:     { label: "Spices & Condiments",  emoji: "🧂" },
  condiment: { label: "Spices & Condiments",  emoji: "🧂" },
  frozen:    { label: "Frozen",               emoji: "🧊" },
  bakery:    { label: "Bakery",               emoji: "🍞" },
  grain:     { label: "Bakery",               emoji: "🍞" },
  other:     { label: "Other",               emoji: "📦" },
};

const CATEGORY_SORT_ORDER = [
  "produce", "protein", "dairy",
  "pantry", "canned",
  "spices", "spice", "condiment",
  "frozen", "bakery", "grain",
  "other",
];

function categoryLabel(cat: string | null): string {
  const c = cat || "other";
  const cfg = CATEGORY_CONFIG[c];
  return cfg ? `${cfg.emoji} ${cfg.label}` : c;
}

function categorySort(cat: string | null): number {
  const idx = CATEGORY_SORT_ORDER.indexOf(cat || "other");
  return idx === -1 ? 999 : idx;
}

// ─── Date range helpers ───────────────────────────────────────────────────────
type RangePreset = "this_week" | "next_week" | "custom";

function localDateStr(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

function getMonday(date: Date): string {
  const d = new Date(date);
  const day = d.getDay();
  d.setDate(d.getDate() - day + (day === 0 ? -6 : 1));
  return localDateStr(d);
}

function addDays(dateStr: string, days: number): string {
  const d = new Date(dateStr + "T12:00:00");
  d.setDate(d.getDate() + days);
  return localDateStr(d);
}

function getPresetRange(preset: RangePreset, customRange: { start: string; end: string }) {
  if (preset === "this_week") {
    const start = getMonday(new Date());
    return { start, end: addDays(start, 6) };
  }
  if (preset === "next_week") {
    const now = new Date();
    now.setDate(now.getDate() + 7);
    const start = getMonday(now);
    return { start, end: addDays(start, 6) };
  }
  return customRange;
}

function getDayLabel(dateStr: string): string {
  const d = new Date(dateStr + "T12:00:00");
  return d.toLocaleDateString("en-US", { weekday: "short" });
}

// ─── Types ────────────────────────────────────────────────────────────────────
interface HouseholdGroceryItem extends GroceryItemType {
  owner_name?: string;
}

interface MealPlanSummaryItem {
  id: string;
  planned_date: string;
  meal_type: string;
  servings: number;
  is_household?: boolean;
  owner_name?: string | null;
  recipe: {
    id: string;
    title: string;
    image_url: string | null;
    prep_time_minutes: number | null;
    cook_time_minutes: number | null;
  };
}

type FilterMode = "to_buy" | "checked" | "all";
type GroupMode = "category" | "meal";

// ─── Main component ───────────────────────────────────────────────────────────
export default function GroceryList() {
  const router = useRouter();

  // Range
  const [rangePreset, setRangePreset] = useState<RangePreset>("this_week");
  const [customRange, setCustomRange] = useState(() => {
    const start = getMonday(new Date());
    return { start, end: addDays(start, 6) };
  });
  const [rangePickerOpen, setRangePickerOpen] = useState(false);

  // Filter & grouping
  const [filter, setFilter] = useState<FilterMode>("to_buy");
  const [groupMode, setGroupMode] = useState<GroupMode>("category");
  const [groupMenuOpen, setGroupMenuOpen] = useState(false);
  const groupMenuRef = useRef<HTMLDivElement>(null);
  const [expandedGroups, setExpandedGroups] = useState<Set<string>>(new Set());

  // Meal plan summary
  const [mealsExpanded, setMealsExpanded] = useState(true);
  const [excludedMealIds, setExcludedMealIds] = useState<Set<string>>(new Set());

  // Data (SWR-cached)
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState("");
  const [autoGenerated, setAutoGenerated] = useState(false);

  // Cost estimate
  const [estimating, setEstimating] = useState(false);
  const [costEstimate, setCostEstimate] = useState<{
    items: { name: string; estimate_low: number; estimate_high: number }[];
    total_low: number;
    total_high: number;
    notes: string;
  } | null>(null);

  // Sheets
  const [addSheetOpen, setAddSheetOpen] = useState(false);
  const [editItem, setEditItem] = useState<GroceryItemType | null>(null);
  const [orderOnlineOpen, setOrderOnlineOpen] = useState(false);

  const dateRange = useMemo(
    () => getPresetRange(rangePreset, customRange),
    [rangePreset, customRange]
  );

  // ── SWR fetch ──────────────────────────────────────────────────────────────
  const swrKey = `/api/grocery-list?date_start=${dateRange.start}&date_end=${dateRange.end}`;
  const { data: groceryData, isLoading: loading, mutate: mutateGrocery } = useSWR(
    swrKey, apiFetcher, { revalidateOnFocus: false, dedupingInterval: 5000 }
  );

  const list: GroceryListType | null = groceryData?.list ?? null;
  const items: GroceryItemType[] = groceryData?.items ?? [];
  const householdItems: HouseholdGroceryItem[] = groceryData?.householdItems ?? [];
  const mealPlanChanged: boolean = groceryData?.meal_plan_changed ?? false;
  const meals: MealPlanSummaryItem[] = groceryData?.meals ?? [];

  // ── Auto-generate when there's no list yet ────────────────────────────────
  useEffect(() => {
    if (!loading && !list && !generating && !autoGenerated) {
      setAutoGenerated(true);
      handleAutoGenerate();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loading, list]);

  // ── Auto-sync when meal plan has changed ──────────────────────────────────
  const lastSyncedAt = useRef<string | null>(null);
  useEffect(() => {
    if (!loading && mealPlanChanged && list && !generating) {
      // Only auto-sync once per generation cycle
      const generatedAt = list.generated_at ?? "";
      if (lastSyncedAt.current !== generatedAt) {
        lastSyncedAt.current = generatedAt;
        handleAutoGenerate();
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loading, mealPlanChanged, list?.generated_at]);

  async function handleAutoGenerate() {
    setGenerating(true);
    try {
      const res = await fetch("/api/grocery-list", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ date_start: dateRange.start, date_end: dateRange.end }),
      });
      if (!res.ok) return;
      await mutateGrocery();
    } catch {
      // Silently fail
    } finally {
      setGenerating(false);
    }
  }

  // ── Generate / regenerate ──────────────────────────────────────────────────
  async function handleGenerate() {
    setGenerating(true);
    setError("");
    try {
      const res = await fetch("/api/grocery-list", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ date_start: dateRange.start, date_end: dateRange.end }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error);
      await mutateGrocery();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to generate");
    } finally {
      setGenerating(false);
    }
  }

  // ── Remove meal (optimistic — instant UI, background regenerate) ────────────
  async function handleRemoveMeal(planId: string) {
    // Find the meal being removed to know which recipe it references
    const removedMeal = meals.find((m) => m.id === planId);
    const removedRecipeTitle = removedMeal?.recipe?.title;

    // Optimistically: remove meal from local list and its grocery items
    const optimistic = groceryData ? {
      ...groceryData,
      meals: (groceryData.meals ?? []).filter((m: MealPlanSummaryItem) => m.id !== planId),
      // If this was the only meal using a recipe, remove those grocery items too
      ...(removedRecipeTitle ? {
        items: (groceryData.items ?? []).map((item: GroceryItemType) => {
          if (!item.recipe_sources?.includes(removedRecipeTitle)) return item;
          // Check if other remaining meals also use this recipe
          const otherMealsWithRecipe = (groceryData.meals ?? []).filter(
            (m: MealPlanSummaryItem) => m.id !== planId && m.recipe?.title === removedRecipeTitle
          );
          if (otherMealsWithRecipe.length > 0) return item;
          // This was the only meal with this recipe — remove or update recipe_sources
          const newSources = item.recipe_sources.filter((s: string) => s !== removedRecipeTitle);
          if (newSources.length === 0) return null; // remove entirely
          return { ...item, recipe_sources: newSources };
        }).filter(Boolean),
      } : {}),
    } : undefined;
    mutateGrocery(optimistic, false);

    // Delete the meal plan, then regenerate grocery list so DB stays in sync
    try {
      const removeRes = await fetch("/api/meal-plan/remove", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ plan_id: planId }),
      });
      if (!removeRes.ok) throw new Error("Remove failed");

      // Regenerate grocery list in background to sync DB items with current meals
      await fetch("/api/grocery-list", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ date_start: dateRange.start, date_end: dateRange.end }),
      });
      // Revalidate to pick up the regenerated list
      await mutateGrocery();
    } catch {
      // Revert on failure
      mutateGrocery();
    }
  }

  // ── Toggle checked (optimistic) ───────────────────────────────────────────
  async function handleToggle(id: string, checked: boolean) {
    const optimistic = groceryData ? {
      ...groceryData,
      items: groceryData.items?.map((i: GroceryItemType) => i.id === id ? { ...i, checked } : i) ?? [],
      householdItems: groceryData.householdItems?.map((i: HouseholdGroceryItem) => i.id === id ? { ...i, checked } : i) ?? [],
    } : undefined;
    mutateGrocery(optimistic, false);

    try {
      await fetch("/api/grocery-list/items", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id, checked }),
      });
    } catch {
      await mutateGrocery();
    }
  }

  // ── Save edit ──────────────────────────────────────────────────────────────
  async function handleSaveEdit(
    id: string,
    changes: { name?: string; amount?: string | null; unit?: string | null; category?: string | null }
  ) {
    try {
      await fetch("/api/grocery-list/items", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id, ...changes }),
      });
      await mutateGrocery();
    } catch {
      // ignore
    }
  }

  // ── Delete item (optimistic) ──────────────────────────────────────────────
  async function handleDelete(id: string) {
    const optimistic = groceryData ? {
      ...groceryData,
      items: (groceryData.items ?? []).filter((i: GroceryItemType) => i.id !== id),
      householdItems: (groceryData.householdItems ?? []).filter((i: HouseholdGroceryItem) => i.id !== id),
    } : undefined;
    mutateGrocery(optimistic, false);

    try {
      await fetch("/api/grocery-list/items", {
        method: "DELETE",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id }),
      });
    } catch {
      await mutateGrocery();
    }
  }

  // ── Add custom item ────────────────────────────────────────────────────────
  function handleItemAdded(item: GroceryItemType) {
    const optimistic = groceryData ? {
      ...groceryData,
      items: [...(groceryData.items ?? []), item],
    } : undefined;
    mutateGrocery(optimistic, false);
    if (!list) mutateGrocery();
  }

  // ── Estimate cost ──────────────────────────────────────────────────────────
  async function handleEstimateCost() {
    const buyItems = activeItems.filter((i) => !i.checked);
    if (buyItems.length === 0) return;
    setEstimating(true);
    setCostEstimate(null);
    try {
      const res = await fetch("/api/grocery-list/estimate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          items: buyItems.map((i) => ({
            name: i.name_override ?? i.name,
            amount: i.amount_override ?? i.amount,
            unit: i.unit_override ?? i.unit,
            category: i.category_override ?? i.category,
          })),
        }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error);
      setCostEstimate(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to estimate cost");
    } finally {
      setEstimating(false);
    }
  }

  // ── Derived display data ───────────────────────────────────────────────────
  // Build set of recipe titles from excluded meals
  const excludedRecipeTitles = useMemo(() => {
    const titles = new Set<string>();
    for (const meal of meals) {
      if (excludedMealIds.has(meal.id) && meal.recipe?.title) {
        // Only exclude if ALL meals for this recipe are excluded
        const otherMeals = meals.filter(
          (m) => m.recipe?.title === meal.recipe?.title && !excludedMealIds.has(m.id)
        );
        if (otherMeals.length === 0) titles.add(meal.recipe.title);
      }
    }
    return titles;
  }, [meals, excludedMealIds]);

  // Active meals (non-excluded) for display and stats
  const activeMeals = useMemo(() => meals.filter((m) => !excludedMealIds.has(m.id)), [meals, excludedMealIds]);

  const allItems: HouseholdGroceryItem[] = [...items, ...householdItems];

  // Items filtered by exclusions only (not by checked state — tabs handle display)
  const activeItems = useMemo(() => {
    return allItems.filter((item) => {
      if (excludedRecipeTitles.size > 0 && item.recipe_sources?.length) {
        const hasActiveSource = item.recipe_sources.some((s: string) => !excludedRecipeTitles.has(s));
        if (!hasActiveSource) return false;
      }
      return true;
    });
  }, [allItems, excludedRecipeTitles]); // eslint-disable-line react-hooks/exhaustive-deps

  // For Buy tab: unchecked items shown normally; checked items shown crossed out at bottom
  // For Have tab: only checked items
  const filteredItems = useMemo(() => {
    if (filter === "to_buy") return activeItems.filter((i) => !i.checked);
    if (filter === "checked") return activeItems.filter((i) => i.checked);
    return activeItems;
  }, [activeItems, filter]);

  // "Have" items to show crossed out at the bottom of Buy tab
  const haveItemsForBuyTab = useMemo(() => {
    if (filter !== "to_buy") return [];
    return activeItems.filter((i) => i.checked);
  }, [activeItems, filter]);

  // Group by category
  const groupedByCategory = useMemo(() => {
    const map = new Map<string, HouseholdGroceryItem[]>();
    for (const item of filteredItems) {
      const cat = item.category_override ?? item.category ?? "other";
      if (!map.has(cat)) map.set(cat, []);
      map.get(cat)!.push(item);
    }
    return [...map.entries()].sort(([a], [b]) => categorySort(a) - categorySort(b));
  }, [filteredItems]);

  // Group by meal/recipe
  const groupedByMeal = useMemo(() => {
    const map = new Map<string, HouseholdGroceryItem[]>();
    for (const item of filteredItems) {
      if (item.is_custom || !item.recipe_sources?.length) {
        const key = "__custom__";
        if (!map.has(key)) map.set(key, []);
        map.get(key)!.push(item);
      } else {
        for (const source of item.recipe_sources) {
          if (!map.has(source)) map.set(source, []);
          map.get(source)!.push(item);
        }
      }
    }
    // Sort: recipe names alphabetically, custom at end
    return [...map.entries()].sort(([a], [b]) => {
      if (a === "__custom__") return 1;
      if (b === "__custom__") return -1;
      return a.localeCompare(b);
    });
  }, [filteredItems]);

  const grouped = groupMode === "category" ? groupedByCategory : groupedByMeal;

  const toBuyCount = allItems.filter((i) => !i.checked).length;
  const checkedCount = allItems.filter((i) => i.checked).length;
  const hasItems = allItems.length > 0;

  // Navigate week with smart preset detection
  function navigateWeek(days: number) {
    const newStart = addDays(dateRange.start, days);
    const thisWeekStart = getMonday(new Date());
    const nextWeekStart = addDays(thisWeekStart, 7);
    if (newStart === thisWeekStart) {
      setRangePreset("this_week");
    } else if (newStart === nextWeekStart) {
      setRangePreset("next_week");
    } else {
      setRangePreset("custom");
      setCustomRange({ start: newStart, end: addDays(newStart, 6) });
    }
  }

  // Week label for nav bar (e.g. "Mar 30 – Apr 5")
  const weekLabel = useMemo(() => {
    const s = new Date(dateRange.start + "T12:00:00");
    const e = new Date(dateRange.end + "T12:00:00");
    const sm = s.toLocaleDateString("en-US", { month: "short" });
    const em = e.toLocaleDateString("en-US", { month: "short" });
    return s.getMonth() === e.getMonth()
      ? `${sm} ${s.getDate()}\u2013${e.getDate()}`
      : `${sm} ${s.getDate()} \u2013 ${em} ${e.getDate()}`;
  }, [dateRange.start, dateRange.end]);

  return (
    <div className="pb-24" style={{ background: "#faf9f7" }}>

      {/* ── Header: week navigation bar ──────────────────────────────────── */}
      <div className="sticky top-0 z-10 px-4 pt-3 pb-2" style={{ background: "#faf9f7" }}>
        <div className="flex items-center justify-between max-w-3xl mx-auto">
          {/* Left: prev arrow + week label + next arrow */}
          <div className="flex items-center gap-1">
            <button
              onClick={() => navigateWeek(-7)}
              className="w-7 h-7 flex items-center justify-center rounded-full transition-colors active:bg-gray-100"
              style={{ color: "#a09890" }}
            >
              <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
              </svg>
            </button>
            <span className="text-2xl font-black tracking-tight" style={{ color: "#1a1410" }}>
              {weekLabel}
            </span>
            <button
              onClick={() => navigateWeek(7)}
              className="w-7 h-7 flex items-center justify-center rounded-full transition-colors active:bg-gray-100"
              style={{ color: "#a09890" }}
            >
              <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7" />
              </svg>
            </button>
          </div>

          {/* Right: calendar icon with dropdown */}
          <div className="relative">
            <button
              onClick={() => setRangePickerOpen((v) => !v)}
              className="w-8 h-8 flex items-center justify-center rounded-lg transition-colors active:bg-gray-100"
              style={{ color: rangePickerOpen ? "#e8590c" : "#a09890" }}
              aria-label="Select date range"
            >
              <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                <rect x="3" y="4" width="18" height="18" rx="2" strokeLinecap="round" strokeLinejoin="round" />
                <path strokeLinecap="round" strokeLinejoin="round" d="M16 2v4M8 2v4M3 10h18" />
              </svg>
            </button>

            {rangePickerOpen && (
              <>
                <div className="fixed inset-0 z-40" onClick={() => setRangePickerOpen(false)} />
                <div className="absolute right-0 mt-2 w-56 bg-white rounded-2xl shadow-xl border border-gray-100 z-50 overflow-hidden py-1">
                  {(["this_week", "next_week", "custom"] as RangePreset[]).map((preset) => (
                    <button
                      key={preset}
                      onClick={() => {
                        setRangePreset(preset);
                        if (preset !== "custom") setRangePickerOpen(false);
                      }}
                      className={`w-full text-left px-4 py-2.5 text-sm transition-colors ${
                        rangePreset === preset
                          ? "text-orange-600 bg-orange-50 font-medium"
                          : "text-gray-700 hover:bg-gray-50"
                      }`}
                    >
                      {preset === "this_week" ? "This week" : preset === "next_week" ? "Next week" : "Custom range"}
                    </button>
                  ))}

                  {rangePreset === "custom" && (
                    <div className="px-4 pb-3 pt-1 border-t border-gray-100 space-y-2">
                      <div>
                        <label className="block text-[11px] text-gray-400 mb-1">From</label>
                        <input
                          type="date"
                          value={customRange.start}
                          onChange={(e) => {
                            const start = e.target.value;
                            setCustomRange((r) => ({ start, end: r.end < start ? addDays(start, 6) : r.end }));
                          }}
                          className="w-full text-xs px-2.5 py-1.5 border border-gray-200 rounded-lg bg-gray-50 outline-none focus:ring-1 focus:ring-orange-300"
                        />
                      </div>
                      <div>
                        <label className="block text-[11px] text-gray-400 mb-1">To</label>
                        <input
                          type="date"
                          value={customRange.end}
                          min={customRange.start}
                          onChange={(e) => setCustomRange((r) => ({ ...r, end: e.target.value }))}
                          className="w-full text-xs px-2.5 py-1.5 border border-gray-200 rounded-lg bg-gray-50 outline-none focus:ring-1 focus:ring-orange-300"
                        />
                      </div>
                      <button
                        onClick={() => setRangePickerOpen(false)}
                        className="w-full text-xs font-medium text-white bg-orange-500 rounded-lg py-1.5"
                      >
                        Apply
                      </button>
                    </div>
                  )}
                </div>
              </>
            )}
          </div>
        </div>
      </div>

      {/* Centered content container */}
      <div className="max-w-3xl mx-auto">

      {error && (
        <div className="mx-4 mt-3 px-4 py-2.5 bg-red-50 border border-red-100 rounded-xl text-sm text-red-600">
          {error}
        </div>
      )}

      {/* ── Meal Plan Summary ──────────────────────────────────────────────── */}
      {!loading && (
        <div className="mx-4 mt-2">
          <button
            onClick={() => setMealsExpanded((v) => !v)}
            className="flex items-center gap-2 w-full text-left py-2"
          >
            <h2 className="text-xs font-black tracking-widest uppercase" style={{ color: "#a09890" }}>
              Meals ({activeMeals.length})
            </h2>
            <svg
              className={`w-3.5 h-3.5 transition-transform ${mealsExpanded ? "rotate-180" : ""}`}
              style={{ color: "#a09890" }}
              fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}
            >
              <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
            </svg>
          </button>

          {mealsExpanded && (
            <div className="flex gap-3 overflow-x-auto pb-2 -mx-4 px-4 snap-x snap-mandatory" style={{ scrollbarWidth: "none", WebkitOverflowScrolling: "touch" }}>
              {meals.map((meal) => {
                const isExcluded = excludedMealIds.has(meal.id);
                return (
                  <div
                    key={meal.id}
                    className={`relative flex-shrink-0 snap-start rounded-2xl overflow-hidden transition-all duration-200 ${isExcluded ? "opacity-40 grayscale" : ""}`}
                    style={{ width: 152, boxShadow: "0 2px 16px rgba(0,0,0,0.08)" }}
                  >
                    {/* Image */}
                    <div className="relative w-full aspect-[4/3] bg-gray-100">
                      {meal.recipe?.image_url ? (
                        <Image
                          src={meal.recipe.image_url}
                          alt={meal.recipe?.title ?? ""}
                          fill
                          className="object-cover"
                          sizes="152px"
                        />
                      ) : (
                        <div className="w-full h-full flex items-center justify-center text-2xl bg-gradient-to-br from-orange-50 to-amber-50">🍽</div>
                      )}
                      {/* Gradient overlay for text readability */}
                      <div className="absolute inset-0 bg-gradient-to-t from-black/50 via-transparent to-transparent" />
                      {/* Day badge */}
                      <span className="absolute top-2 left-2 text-[10px] font-bold uppercase tracking-wide px-2 py-0.5 rounded-full bg-white/90 text-gray-700 backdrop-blur-sm">
                        {getDayLabel(meal.planned_date)}
                      </span>
                      {/* Household badge */}
                      {meal.is_household && meal.owner_name && (
                        <span className="absolute top-2 right-2 text-[9px] font-bold px-1.5 py-0.5 rounded-full bg-purple-500/90 text-white backdrop-blur-sm">
                          {meal.owner_name}
                        </span>
                      )}
                      {/* Remove / exclude button */}
                      {!isExcluded && (
                        <button
                          onClick={() => meal.is_household
                            ? setExcludedMealIds((prev) => new Set(prev).add(meal.id))
                            : handleRemoveMeal(meal.id)
                          }
                          className="absolute top-2 right-2 w-6 h-6 flex items-center justify-center rounded-full bg-black/30 text-white/80 hover:bg-black/50 hover:text-white backdrop-blur-sm transition-colors"
                          style={meal.is_household && meal.owner_name ? { top: "auto", bottom: 42, right: 8 } : undefined}
                          aria-label={`Remove ${meal.recipe?.title}`}
                        >
                          <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                            <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                          </svg>
                        </button>
                      )}
                    </div>
                    {/* Info */}
                    <div className="bg-white px-2.5 py-2">
                      <p className={`text-[13px] font-semibold leading-tight line-clamp-2 ${isExcluded ? "line-through text-gray-400" : "text-gray-800"}`}>
                        {meal.recipe?.title}
                      </p>
                      <p className="text-[10px] text-gray-400 mt-0.5 capitalize">{meal.meal_type}</p>
                    </div>
                    {/* Add back overlay for excluded */}
                    {isExcluded && (
                      <button
                        onClick={() => setExcludedMealIds((prev) => { const n = new Set(prev); n.delete(meal.id); return n; })}
                        className="absolute inset-0 flex items-center justify-center"
                      >
                        <span className="text-[11px] font-bold text-orange-600 bg-white/90 px-3 py-1.5 rounded-full shadow-sm backdrop-blur-sm">
                          Add back
                        </span>
                      </button>
                    )}
                  </div>
                );
              })}
              {/* + Add meal card */}
              <button
                onClick={() => router.push("/recipes?tab=meal-plan")}
                className="flex-shrink-0 snap-start rounded-2xl overflow-hidden flex flex-col items-center justify-center gap-2 transition-colors hover:bg-gray-100"
                style={{ width: 152, minHeight: 152, background: "#f9f7f5", border: "2px dashed #e0dbd6" }}
              >
                <div className="w-10 h-10 rounded-full flex items-center justify-center" style={{ background: "#eee9e3" }}>
                  <svg className="w-5 h-5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M12 4v16m8-8H4" />
                  </svg>
                </div>
                <span className="text-xs font-medium text-gray-400">Add meal</span>
              </button>
            </div>
          )}
        </div>
      )}


      {/* ── List header + filter + view toggle ─────────────────────────── */}
      {hasItems && (
        <div className="mx-4 mt-4 mb-1">
          <h2 className="text-xs font-black tracking-widest uppercase" style={{ color: "#a09890" }}>
            List ({toBuyCount})
          </h2>
        </div>
      )}
      {hasItems && (
        <div className="mx-4 mt-3">
          <div className="flex items-center gap-2">
            {/* Full-width sliding pill toggle */}
            <div className="flex flex-1 bg-gray-100 rounded-2xl p-1 relative overflow-hidden">
              <div
                className="absolute top-1 bottom-1 rounded-xl bg-white shadow-sm transition-all duration-300 ease-out"
                style={{
                  width: "calc(50% - 4px)",
                  left: filter === "to_buy" ? 4 : "calc(50% + 0px)",
                }}
              />
              {([
                { key: "to_buy",  label: `Buy${toBuyCount > 0 ? ` (${toBuyCount})` : ""}` },
                { key: "checked", label: `Have${checkedCount > 0 ? ` (${checkedCount})` : ""}` },
              ] as { key: FilterMode; label: string }[]).map(({ key, label }) => (
                <button
                  key={key}
                  onClick={() => setFilter(key)}
                  className={`flex-1 py-2.5 px-4 rounded-xl text-xs font-bold transition-colors duration-200 relative z-10 ${
                    filter === key ? "text-gray-900" : "text-gray-400"
                  }`}
                >
                  {label}
                </button>
              ))}
            </div>
            {/* View mode dropdown */}
            <div className="relative flex-shrink-0" ref={groupMenuRef}>
              <button
                onClick={() => setGroupMenuOpen((v) => !v)}
                className="flex items-center gap-1.5 text-xs font-semibold px-3 py-2 rounded-full transition-colors"
                style={{ background: "#f0ede8", color: "#7a7068" }}
              >
                {groupMode === "category" ? "Category" : "Meal"}
                <svg className={`w-3 h-3 opacity-60 transition-transform ${groupMenuOpen ? "rotate-180" : ""}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
                </svg>
              </button>
              {groupMenuOpen && (
                <>
                  <div className="fixed inset-0 z-40" onClick={() => setGroupMenuOpen(false)} />
                  <div className="absolute right-0 mt-2 w-40 bg-white rounded-2xl shadow-xl border border-gray-100 z-50 py-1.5 overflow-hidden"
                    style={{ boxShadow: "0 8px 32px rgba(0,0,0,0.12)" }}>
                    {([
                      { key: "category", label: "By Category" },
                      { key: "meal", label: "By Meal" },
                    ] as { key: GroupMode; label: string }[]).map(({ key, label }) => (
                      <button
                        key={key}
                        onClick={() => { setGroupMode(key); setGroupMenuOpen(false); }}
                        className="w-full flex items-center justify-between px-4 py-2.5 text-xs font-semibold transition-colors hover:bg-gray-50"
                        style={{ color: groupMode === key ? "#1a1410" : "#6b6560" }}
                      >
                        <span>{label}</span>
                        {groupMode === key && (
                          <svg className="w-3.5 h-3.5 text-gray-900" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                            <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                          </svg>
                        )}
                      </button>
                    ))}
                  </div>
                </>
              )}
            </div>
          </div>
        </div>
      )}

      {/* ── Content ─────────────────────────────────────────────────────────── */}
      {loading ? (
        <div className="mx-4 mt-3 space-y-3">
          {[1, 2, 3].map((n) => (
            <div key={n} className="rounded-3xl overflow-hidden" style={{ boxShadow: "0 2px 16px rgba(0,0,0,0.06)" }}>
              <div className="p-4 bg-white">
                <div className="h-2.5 w-20 skeleton-warm rounded-full mb-4" />
                <div className="space-y-3">
                  {[1, 2].map((m) => (
                    <div key={m} className="flex items-center gap-3">
                      <div className="w-5 h-5 rounded-lg skeleton-warm flex-shrink-0" />
                      <div className="h-2.5 flex-1 skeleton-warm rounded-full" />
                    </div>
                  ))}
                </div>
              </div>
            </div>
          ))}
        </div>

      ) : !list ? (
        <div className="mx-4 mt-6 text-center animate-fade-slide-up">
          <div className="bg-white rounded-3xl px-6 py-12" style={{ boxShadow: "0 2px 16px rgba(0,0,0,0.06)" }}>
            <p className="text-5xl mb-4">🛒</p>
            <p className="font-black text-lg mb-1" style={{ color: "#1a1410" }}>No grocery list yet</p>
            <p className="text-sm mb-7" style={{ color: "#a09890" }}>
              Add meals to your plan, then generate your list.
            </p>
            <button
              onClick={handleGenerate}
              disabled={generating}
              className="px-7 py-3 rounded-2xl text-sm font-black text-white transition-all active:scale-95 disabled:opacity-50"
              style={{ background: "#1a1410" }}
            >
              {generating ? "Syncing\u2026" : "Generate from Plan"}
            </button>
          </div>
        </div>

      ) : grouped.length === 0 ? (
        <div className="mx-4 mt-6 text-center">
          {allItems.length === 0 ? (
            <div className="bg-white rounded-2xl border border-gray-100 px-6 py-10">
              <p className="text-4xl mb-4">✨</p>
              <p className="text-gray-800 font-semibold text-base mb-1">List cleared</p>
              <p className="text-gray-400 text-sm mb-1">
                Add meals to your plan, then tap generate to build your list.
              </p>
            </div>
          ) : filter === "to_buy" ? (
            <div className="bg-white rounded-2xl border border-gray-100 px-6 py-10">
              <p className="text-4xl mb-3">🎉</p>
              <p className="text-gray-800 font-semibold text-base mb-1">All done!</p>
              <p className="text-gray-400 text-sm">Everything is checked off your list.</p>
            </div>
          ) : filter === "checked" ? (
            <div className="py-10">
              <p className="text-gray-400 text-sm">Nothing marked as have yet.</p>
            </div>
          ) : (
            <div className="py-10">
              <p className="text-gray-400 text-sm">Your list is empty.</p>
            </div>
          )}
        </div>

      ) : (
        /* Grouped list */
        <div className="mx-4 mt-3 space-y-3">
          {grouped.map(([groupKey, groupItems], gi) => {
            const isExpanded = expandedGroups.has(groupKey);
            const toggleGroup = () => setExpandedGroups((prev) => {
              const next = new Set(prev);
              if (next.has(groupKey)) next.delete(groupKey);
              else next.add(groupKey);
              return next;
            });

            return (
              <div
                key={groupKey}
                className="bg-white rounded-3xl overflow-hidden"
                style={{
                  boxShadow: "0 2px 16px rgba(0,0,0,0.06)",
                  animation: `fadeSlideUp 0.4s cubic-bezier(0.16,1,0.3,1) ${gi * 60}ms both`,
                }}
              >
                {/* Section header — tap to expand/collapse */}
                <button
                  onClick={toggleGroup}
                  className="w-full flex items-center justify-between px-4 pt-3.5 pb-2"
                >
                  <div className="flex items-center gap-2">
                    <h3 className="text-xs font-black tracking-widest uppercase" style={{ color: "#a09890" }}>
                      {groupMode === "category"
                        ? categoryLabel(groupKey)
                        : groupKey === "__custom__"
                          ? "📦 Custom & Added"
                          : `🍽 ${groupKey}`
                      }
                    </h3>
                    <span className="text-[10px] font-medium px-1.5 py-0.5 rounded-full" style={{ background: "#f0ede8", color: "#a09890" }}>
                      {groupItems.length}
                    </span>
                  </div>
                  <div className="flex items-center gap-1.5">
                    {/* + Add item to this category */}
                    <span
                      role="button"
                      onClick={(e) => { e.stopPropagation(); setAddSheetOpen(true); }}
                      className="w-7 h-7 flex items-center justify-center rounded-full hover:bg-gray-100 transition-colors"
                      style={{ color: "#a09890" }}
                    >
                      <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M12 4v16m8-8H4" />
                      </svg>
                    </span>
                    {/* Chevron */}
                    <svg
                      className={`w-4 h-4 transition-transform duration-200 ${isExpanded ? "rotate-180" : ""}`}
                      style={{ color: "#c0b8b0" }}
                      fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}
                    >
                      <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
                    </svg>
                  </div>
                </button>
                {/* Items — collapsible */}
                {isExpanded && (
                  <div className="px-3 pb-2 space-y-0.5">
                    {groupItems.map((item) => (
                      <GroceryItem
                        key={item.id}
                        item={item}
                        onToggle={handleToggle}
                        onEdit={setEditItem}
                        onDelete={handleDelete}
                        ownerName={item.owner_name}
                        haveMode={filter === "checked"}
                      />
                    ))}
                  </div>
                )}
              </div>
            );
          })}

          {/* "Already Have" section — shown at bottom of Buy tab */}
          {filter === "to_buy" && haveItemsForBuyTab.length > 0 && (() => {
            const haveKey = "__already_have__";
            const isHaveExpanded = expandedGroups.has(haveKey);
            const toggleHave = () => setExpandedGroups((prev) => {
              const next = new Set(prev);
              if (next.has(haveKey)) next.delete(haveKey);
              else next.add(haveKey);
              return next;
            });
            return (
              <div
                className="bg-white rounded-3xl overflow-hidden"
                style={{ boxShadow: "0 2px 16px rgba(0,0,0,0.06)" }}
              >
                <button
                  onClick={toggleHave}
                  className="w-full flex items-center justify-between px-4 pt-3.5 pb-2"
                >
                  <div className="flex items-center gap-2">
                    <h3 className="text-xs font-black tracking-widest uppercase" style={{ color: "#a09890" }}>
                      ✅ Already have
                    </h3>
                    <span className="text-[10px] font-medium px-1.5 py-0.5 rounded-full" style={{ background: "#f0ede8", color: "#a09890" }}>
                      {haveItemsForBuyTab.length}
                    </span>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <svg
                      className={`w-4 h-4 transition-transform duration-200 ${isHaveExpanded ? "rotate-180" : ""}`}
                      style={{ color: "#c0b8b0" }}
                      fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}
                    >
                      <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
                    </svg>
                  </div>
                </button>
                {isHaveExpanded && (
                  <div className="px-4 pb-3">
                    {haveItemsForBuyTab.map((item) => {
                      const displayName = item.name_override ?? item.name;
                      const displayAmount = item.amount_override ?? item.amount;
                      const displayUnit = item.unit_override ?? item.unit;
                      return (
                        <div
                          key={item.id}
                          className="flex items-center gap-2.5 py-1.5"
                          style={{ borderBottom: "1px solid #f5f3f0" }}
                        >
                          <svg className="w-3.5 h-3.5 text-green-400 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                            <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                          </svg>
                          <span className="text-sm text-gray-400 line-through capitalize flex-1 min-w-0 truncate">
                            {displayName}
                          </span>
                          {displayAmount && (
                            <span className="text-xs text-gray-300 flex-shrink-0">
                              {displayAmount}{displayUnit ? ` ${displayUnit}` : ""}
                            </span>
                          )}
                          <button
                            onClick={(e) => { e.stopPropagation(); handleToggle(item.id, false); }}
                            className="text-[10px] font-semibold text-orange-400 hover:text-orange-600 flex-shrink-0 px-1"
                          >
                            Need
                          </button>
                        </div>
                      );
                    })}
                  </div>
                )}
              </div>
            );
          })()}

          {/* Cost estimate result */}
          {filter === "to_buy" && costEstimate && (
            <div
              className="bg-white rounded-3xl overflow-hidden"
              style={{ boxShadow: "0 2px 16px rgba(0,0,0,0.06)" }}
            >
              <div className="px-4 pt-4 pb-2">
                <div className="flex items-center justify-between">
                  <h3 className="text-xs font-black tracking-widest uppercase" style={{ color: "#a09890" }}>
                    Estimated Cost
                  </h3>
                  <button
                    onClick={() => setCostEstimate(null)}
                    className="w-6 h-6 flex items-center justify-center rounded-full hover:bg-gray-100 transition-colors"
                    style={{ color: "#c0b8b0" }}
                  >
                    <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                  </button>
                </div>
                <div className="flex items-baseline gap-1 mt-2">
                  <span className="text-2xl font-bold text-gray-800">
                    ${costEstimate.total_low.toFixed(0)}
                  </span>
                  <span className="text-lg text-gray-400 font-medium">
                    &ndash; ${costEstimate.total_high.toFixed(0)}
                  </span>
                </div>
                {costEstimate.notes && (
                  <p className="text-[11px] text-gray-400 mt-1">{costEstimate.notes}</p>
                )}
              </div>
              <div className="px-4 pb-2 pt-1">
                {costEstimate.items.map((ci, idx) => (
                  <div
                    key={idx}
                    className="flex items-center justify-between py-1.5"
                    style={idx < costEstimate.items.length - 1 ? { borderBottom: "1px solid #f5f3f0" } : undefined}
                  >
                    <span className="text-[13px] text-gray-600 capitalize truncate flex-1 min-w-0 mr-2">
                      {ci.name}
                    </span>
                    <span className="text-[12px] text-gray-400 flex-shrink-0 tabular-nums">
                      ${ci.estimate_low.toFixed(2)} &ndash; ${ci.estimate_high.toFixed(2)}
                    </span>
                  </div>
                ))}
              </div>
              {/* Online ordering teaser */}
              <div className="px-4 pb-4 pt-2">
                <div
                  className="w-full flex items-center justify-center gap-2.5 py-3 rounded-2xl"
                  style={{ background: "#f5f3f0" }}
                >
                  <svg className="w-4.5 h-4.5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 00-3 3h15.75m-12.75-3h11.218c1.121-2.3 2.1-4.684 2.924-7.138a60.114 60.114 0 00-16.536-1.84M7.5 14.25L5.106 5.272M6 20.25a.75.75 0 11-1.5 0 .75.75 0 011.5 0zm12.75 0a.75.75 0 11-1.5 0 .75.75 0 011.5 0z" />
                  </svg>
                  <span className="text-sm font-medium text-gray-400">Online ordering coming soon</span>
                </div>
              </div>
            </div>
          )}

          {/* Bottom action — Estimate Cost (Buy tab, hidden when estimate shown) or Add Item (Have tab) */}
          {filter === "to_buy" ? (
            toBuyCount > 0 && !costEstimate && (
              <button
                onClick={handleEstimateCost}
                disabled={estimating}
                className="w-full flex items-center justify-center gap-2.5 py-3.5 bg-white rounded-3xl border border-gray-200 hover:border-orange-300 hover:bg-orange-50/30 transition-colors disabled:opacity-60"
                style={{ boxShadow: "0 2px 16px rgba(0,0,0,0.06)" }}
              >
                {estimating ? (
                  <>
                    <div className="w-4 h-4 border-2 border-orange-500 border-t-transparent rounded-full animate-spin" />
                    <span className="text-sm font-semibold text-gray-500">Estimating...</span>
                  </>
                ) : (
                  <>
                    <svg className="w-5 h-5 text-orange-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M12 6v12m-3-2.818l.879.659c1.171.879 3.07.879 4.242 0 1.172-.879 1.172-2.303 0-3.182C13.536 12.219 12.768 12 12 12c-.725 0-1.45-.22-2.003-.659-1.106-.879-1.106-2.303 0-3.182s2.9-.879 4.006 0l.415.33M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    <span className="text-sm font-semibold text-gray-700">Estimate cost</span>
                  </>
                )}
              </button>
            )
          ) : filter === "checked" && (
            <button
              onClick={() => setAddSheetOpen(true)}
              className="w-full flex items-center justify-center gap-2.5 py-3.5 bg-white rounded-3xl border border-gray-200 hover:border-orange-300 hover:bg-orange-50/30 transition-colors"
              style={{ boxShadow: "0 2px 16px rgba(0,0,0,0.06)" }}
            >
              <svg className="w-5 h-5 text-orange-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 4v16m8-8H4" />
              </svg>
              <span className="text-sm font-semibold text-gray-700">Add item</span>
            </button>
          )}
        </div>
      )}

      </div>{/* close max-w-3xl container */}

      {/* Generating indicator — inline, non-blocking */}
      {generating && (
        <div className="mx-4 mt-3 flex items-center justify-center gap-2 py-4">
          <div className="w-4 h-4 border-2 border-orange-500 border-t-transparent rounded-full animate-spin" />
          <p className="text-xs font-medium text-gray-500">Updating list\u2026</p>
        </div>
      )}

      {/* Sheets */}
      <AddItemSheet
        isOpen={addSheetOpen}
        listId={list?.id ?? null}
        dateStart={dateRange.start}
        dateEnd={dateRange.end}
        onClose={() => setAddSheetOpen(false)}
        onAdd={handleItemAdded}
      />

      <EditItemSheet
        item={editItem}
        onClose={() => setEditItem(null)}
        onSave={handleSaveEdit}
        onDelete={handleDelete}
      />

      <OrderOnlineSheet
        isOpen={orderOnlineOpen}
        onClose={() => setOrderOnlineOpen(false)}
        items={allItems}
      />
    </div>
  );
}
